import type { BattleScenario } from "../types";

export const cityStreetAmbushScenario: BattleScenario = {
  id: "battle_001_city_street_ambush",
  title: "Battle 001 — City Street Ambush",
  map: {
    id: "city_street_ambush_map",
    title: "City Street Ambush",
    subtitle: "Outside the hero's home, after the pickpocket child lures him into a thug ambush.",
    cols: 12,
    rows: 8,
    backgroundAssetKey: "first_battle_map",
    terrain: [
      ["wall", "wall", "grass", "grass", "stone", "stone", "stone", "stone", "cover", "cover", "wall", "wall"],
      ["wall", "stone", "grass", "stone", "stone", "stone", "stone", "stone", "stone", "cover", "stone", "wall"],
      ["fence", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "fence"],
      ["grass", "stone", "stone", "grass", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "cover"],
      ["stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"],
      ["road", "road", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "cover", "cover"],
      ["wall", "road", "road", "stone", "stone", "stone", "cover", "cover", "stone", "stone", "grass", "grass"],
      ["wall", "wall", "road", "road", "stone", "stone", "cover", "wall", "wall", "grass", "grass", "wall"],
    ],
    storyNotes: [
      "The hero is still in plain real-world clothes.",
      "A child pretends to need help, steals the hero's money, then hides behind the thugs.",
      "The child is a visible non-combatant: cannot move, attack, or be targeted.",
      "This map should stay bright, readable, and JRPG/anime-styled, not dark or grainy.",
    ],
  },
  units: [
    {
      id: "hero_plain_clothes",
      name: "Hero",
      side: "ally",
      classKey: "hero",
      role: "Plain Clothes / Beginner Fighter",
      x: 3,
      y: 4,
      hp: 100,
      maxHp: 100,
      attack: 24,
      defense: 12,
      move: 4,
      range: 1,
      canAct: true,
      targetable: true,
      note: "First battle test unit. Later gains class, skills, and cooldowns.",
    },
    {
      id: "thug_knife_1",
      name: "Street Thug",
      side: "enemy",
      classKey: "thug",
      role: "Melee",
      x: 7,
      y: 2,
      hp: 60,
      maxHp: 60,
      attack: 18,
      defense: 8,
      move: 3,
      range: 1,
      canAct: true,
      targetable: true,
    },
    {
      id: "thug_bruiser",
      name: "Bruiser",
      side: "enemy",
      classKey: "thug",
      role: "Heavy Melee",
      x: 9,
      y: 3,
      hp: 80,
      maxHp: 80,
      attack: 20,
      defense: 13,
      move: 3,
      range: 1,
      canAct: true,
      targetable: true,
    },
    {
      id: "thug_knife_2",
      name: "Knife Punk",
      side: "enemy",
      classKey: "rogue",
      role: "Fast Melee",
      x: 8,
      y: 5,
      hp: 55,
      maxHp: 55,
      attack: 16,
      defense: 6,
      move: 4,
      range: 1,
      canAct: true,
      targetable: true,
    },
    {
      id: "pickpocket_child",
      name: "Pickpocket Child",
      side: "neutral",
      classKey: "noncombatant",
      role: "Non-combatant",
      x: 10,
      y: 1,
      hp: 1,
      maxHp: 1,
      attack: 0,
      defense: 0,
      move: 0,
      range: 0,
      canAct: false,
      targetable: false,
      note: "Hidden story unit: cannot move, attack, or be targeted.",
    },
  ],
  victoryCondition: "Defeat all thugs and recover the stolen money.",
  defeatCondition: "Hero is defeated.",
};
